version: '3'
services:
  rds:
    container_name: localrds
    image: mysql/mysql-server:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=rajaravi
      - MYSQL_PASSWORD=rajaravi
      - MYSQL_ROOT_PASSWORD=rajaravi
      - MYSQL_DATABASE=localdb
