# Generated by Django 2.2.6 on 2019-11-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('topics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review_date', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product')),
                ('topic', models.ManyToManyField(related_name='topic', to='topics.Topic')),
            ],
        ),
    ]
