# Generated by Django 2.2.6 on 2019-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keyword', models.CharField(max_length=100)),
                ('case_sensitivity', models.BooleanField(default=False)),
            ],
        ),
    ]
